### ISSUE TITLE
package error,i

### ISSUE THREAD

**Issue by shanshanhao** [LyuJ1998/HandTailor#10]
ImportError: cannot import name 'cusolver' from 'jaxlib'

**Comment by LyuJ1998** [comment]
Hi, this may be because `jax` or `jaxlib` is not installed correctly.  Install a CPU-only version of JAX is enough for HandTailor, please follow [this URL](https://github.com/google/jax#installation). 

As for the `ImportError: cannot import name 'cusolver' from 'jaxlib'`, try [this URL](https://github.com/google/jax/issues/5374).

**Comment by shanshanhao** [comment]
Have solved.Thank u  so much!
