### ISSUE TITLE
align_idx

### ISSUE THREAD

**Issue by ZhengdiYu** [LyuJ1998/HandTailor#13]
Hi, I was wondering that why we use align_idx=9, instead of root_idx 0. Is there any reason? If we will align by root before computing loss anyway, why don't we align by root in the beginning?

**Comment by LyuJ1998** [comment]
Hiiii,
I choose the 9th joint as the root joint because the 9th joint is located at the center of the hand (see this issue #12 for the index of each joint). I think you can also use root_idx 0, but I'm not sure how much impact it will have, I guess it will not change a lot. 
As for the second question, what does "align by root in the beginning" mean? I think it's okay to align the keypoint at any time, but sometimes we need the aligned joint, sometimes we need the joint in the camera space, so be careful about this.

**Comment by ZhengdiYu** [comment]
> Hiiii, I choose the 9th joint as the root joint because the 9th joint is located at the center of the hand (see this issue #12 for the index of each joint). I think you can also use root_idx 0, but I'm not sure how much impact it will have, I guess it will not change a lot. As for the second question, what does "align by root in the beginning" mean? I think it's okay to align the keypoint at any time, but sometimes we need the aligned joint, sometimes we need the joint in the camera space, so be careful about this.

Thanks, 

I was just meaning that, since the mesh will be aligned by root joint before calculating loss in the end, why do we need to align by 9th idx at first?  Why don't we align by 9th idx in the first place instead of doing 2 times of alignment with different idx 9 then 0? I think align by 9th idx is redundant from I see, if we will align by root in the end.

**Comment by LyuJ1998** [comment]
I think we always treat the 9th joint as the root joint for prediction and loss calculation, we didn't align joint or mesh by 0th joint.
