### ISSUE TITLE
jaxlib---Windows

### ISSUE THREAD

**Issue by mywordwin** [LyuJ1998/HandTailor#9]
Hello, how to solve the installation problem of jaxlib on Windows?

**Comment by LyuJ1998** [comment]
Hi, I only run the code on Ubuntu, as for installation JAX on Windows, see https://github.com/google/jax#installation, which says *Windows users can use JAX on CPU and GPU via the Windows Subsystem for Linux. There is some initial native Windows support, but since it is still somewhat immature, there are no binary releases and it must be built from source.*

**Comment by mywordwin** [comment]
> 嗨，我只在 Ubuntu 上运行代码，至于在 Windows 上安装 JAX，请参阅https://github.com/google/jax#installation，其中说_Windows 用户可以通过 Linux 的 Windows 子系统在 CPU 和 GPU 上使用 JAX。有一些最初的原生 Windows 支持，但由于它仍然有些不成熟，因此没有二进制版本，它必须从源代码构建。_

Bro, thanks for the reply, let me give it a try.

**Comment by mywordwin** [comment]
> Hi, I only run the code on Ubuntu, as for installation JAX on Windows, see https://github.com/google/jax#installation, which says _Windows users can use JAX on CPU and GPU via the Windows Subsystem for Linux. There is some initial native Windows support, but since it is still somewhat immature, there are no binary releases and it must be built from source._

Bro, thanks for the reply, let me give it a try.
